/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'change-password': RouteRecordInfo<'change-password', '/change-password', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'ged': RouteRecordInfo<'ged', '/ged', Record<never, never>, Record<never, never>>,
    'ged-id': RouteRecordInfo<'ged-id', '/ged/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ged-atraiter': RouteRecordInfo<'ged-atraiter', '/ged/a-traiter', Record<never, never>, Record<never, never>>,
    'ged-admin': RouteRecordInfo<'ged-admin', '/ged/admin', Record<never, never>, Record<never, never>>,
    'ged-archives': RouteRecordInfo<'ged-archives', '/ged/archives', Record<never, never>, Record<never, never>>,
    'ged-classification': RouteRecordInfo<'ged-classification', '/ged/classification', Record<never, never>, Record<never, never>>,
    'ged-documents': RouteRecordInfo<'ged-documents', '/ged/documents', Record<never, never>, Record<never, never>>,
    'ged-favoris': RouteRecordInfo<'ged-favoris', '/ged/favoris', Record<never, never>, Record<never, never>>,
    'ged-mes-documents': RouteRecordInfo<'ged-mes-documents', '/ged/mes-documents', Record<never, never>, Record<never, never>>,
    'ged-nouveau': RouteRecordInfo<'ged-nouveau', '/ged/nouveau', Record<never, never>, Record<never, never>>,
    'ged-recents': RouteRecordInfo<'ged-recents', '/ged/recents', Record<never, never>, Record<never, never>>,
    'ged-recherche': RouteRecordInfo<'ged-recherche', '/ged/recherche', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'parapheur': RouteRecordInfo<'parapheur', '/parapheur', Record<never, never>, Record<never, never>>,
    'parapheur-id': RouteRecordInfo<'parapheur-id', '/parapheur/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'parapheur-admin': RouteRecordInfo<'parapheur-admin', '/parapheur/admin', Record<never, never>, Record<never, never>>,
    'parapheur-agenda': RouteRecordInfo<'parapheur-agenda', '/parapheur/agenda', Record<never, never>, Record<never, never>>,
    'parapheur-agenda-id': RouteRecordInfo<'parapheur-agenda-id', '/parapheur/agenda/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'parapheur-agenda-avalider': RouteRecordInfo<'parapheur-agenda-avalider', '/parapheur/agenda/a-valider', Record<never, never>, Record<never, never>>,
    'parapheur-agenda-calendrier': RouteRecordInfo<'parapheur-agenda-calendrier', '/parapheur/agenda/calendrier', Record<never, never>, Record<never, never>>,
    'parapheur-agenda-demandes': RouteRecordInfo<'parapheur-agenda-demandes', '/parapheur/agenda/demandes', Record<never, never>, Record<never, never>>,
    'parapheur-agenda-indisponibilites': RouteRecordInfo<'parapheur-agenda-indisponibilites', '/parapheur/agenda/indisponibilites', Record<never, never>, Record<never, never>>,
    'parapheur-agenda-mes-rdv': RouteRecordInfo<'parapheur-agenda-mes-rdv', '/parapheur/agenda/mes-rdv', Record<never, never>, Record<never, never>>,
    'parapheur-agenda-nouveau': RouteRecordInfo<'parapheur-agenda-nouveau', '/parapheur/agenda/nouveau', Record<never, never>, Record<never, never>>,
    'parapheur-appointment-types': RouteRecordInfo<'parapheur-appointment-types', '/parapheur/appointment-types', Record<never, never>, Record<never, never>>,
    'parapheur-audit': RouteRecordInfo<'parapheur-audit', '/parapheur/audit', Record<never, never>, Record<never, never>>,
    'parapheur-delegations': RouteRecordInfo<'parapheur-delegations', '/parapheur/delegations', Record<never, never>, Record<never, never>>,
    'parapheur-dg': RouteRecordInfo<'parapheur-dg', '/parapheur/dg', Record<never, never>, Record<never, never>>,
    'parapheur-document-types': RouteRecordInfo<'parapheur-document-types', '/parapheur/document-types', Record<never, never>, Record<never, never>>,
    'parapheur-instructions': RouteRecordInfo<'parapheur-instructions', '/parapheur/instructions', Record<never, never>, Record<never, never>>,
    'parapheur-meeting-templates': RouteRecordInfo<'parapheur-meeting-templates', '/parapheur/meeting-templates', Record<never, never>, Record<never, never>>,
    'parapheur-meeting-types': RouteRecordInfo<'parapheur-meeting-types', '/parapheur/meeting-types', Record<never, never>, Record<never, never>>,
    'parapheur-nouveau': RouteRecordInfo<'parapheur-nouveau', '/parapheur/nouveau', Record<never, never>, Record<never, never>>,
    'parapheur-reporting': RouteRecordInfo<'parapheur-reporting', '/parapheur/reporting', Record<never, never>, Record<never, never>>,
    'parapheur-reunions-parent': RouteRecordInfo<'parapheur-reunions-parent', '/parapheur/reunions', Record<never, never>, Record<never, never>>,
    'parapheur-reunions': RouteRecordInfo<'parapheur-reunions', '/parapheur/reunions', Record<never, never>, Record<never, never>>,
    'parapheur-reunions-id': RouteRecordInfo<'parapheur-reunions-id', '/parapheur/reunions/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'parapheur-reunions-calendrier': RouteRecordInfo<'parapheur-reunions-calendrier', '/parapheur/reunions/calendrier', Record<never, never>, Record<never, never>>,
    'parapheur-reunions-decisions': RouteRecordInfo<'parapheur-reunions-decisions', '/parapheur/reunions/decisions', Record<never, never>, Record<never, never>>,
    'parapheur-reunions-nouvelle': RouteRecordInfo<'parapheur-reunions-nouvelle', '/parapheur/reunions/nouvelle', Record<never, never>, Record<never, never>>,
    'parapheur-reunions-seance-id': RouteRecordInfo<'parapheur-reunions-seance-id', '/parapheur/reunions/seance/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'parapheur-roles': RouteRecordInfo<'parapheur-roles', '/parapheur/roles', Record<never, never>, Record<never, never>>,
    'parapheur-structures': RouteRecordInfo<'parapheur-structures', '/parapheur/structures', Record<never, never>, Record<never, never>>,
    'parapheur-users': RouteRecordInfo<'parapheur-users', '/parapheur/users', Record<never, never>, Record<never, never>>,
    'parapheur-workflows': RouteRecordInfo<'parapheur-workflows', '/parapheur/workflows', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'reset-password': RouteRecordInfo<'reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
  }
}
