import type { ThemeDefinition } from 'vuetify';

/**
 * Charte graphique DGTCP / Trésor Public (couleurs du logo)
 * Vert · Or · Rouge (drapeau du Mali)
 */
export const staticPrimaryColor = '#0B6B3A';
export const staticPrimaryDarkenColor = '#08512C';
export const brandGold = '#FCD116';
export const brandRed = '#CE1126';
export const brandInk = '#14261A';

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      primary: staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': staticPrimaryDarkenColor,
      secondary: '#8A7420',
      'on-secondary': '#fff',
      'secondary-darken-1': '#6E5C18',
      success: '#0B6B3A',
      'on-success': '#fff',
      'success-darken-1': '#08512C',
      info: '#1F6F8B',
      'on-info': '#fff',
      'info-darken-1': '#195A70',
      warning: '#E0B400',
      'on-warning': '#14261A',
      'warning-darken-1': '#C49C00',
      error: brandRed,
      'on-error': '#fff',
      'error-darken-1': '#B00E20',
      background: '#F4F6F2',
      'on-background': brandInk,
      surface: '#FFFFFF',
      'on-surface': brandInk,
      'grey-50': '#F7F8F5',
      'grey-100': '#EEF1EB',
      'grey-200': '#E0E5DB',
      'grey-300': '#C8D0C1',
      'grey-400': '#9AA893',
      'grey-500': '#73806C',
      'grey-600': '#586352',
      'grey-700': '#434C3E',
      'grey-800': '#2E352B',
      'grey-900': '#1C221B',
      'grey-light': '#F7F8F5',
      'perfect-scrollbar-thumb': '#C8D0C1',
      'skin-bordered-background': '#fff',
      'skin-bordered-surface': '#fff',
      'expansion-panel-text-custom-bg': '#F7F8F5',
    },
    variables: {
      'code-color': brandRed,
      'overlay-scrim-background': brandInk,
      'tooltip-background': brandInk,
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': brandInk,
      'border-opacity': 0.12,
      'table-header-color': '#E8ECE4',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.2,
      'switch-disabled-track-opacity': 0.3,
      'switch-disabled-thumb-opacity': 0.4,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#E8ECE4',
      'shadow-key-umbra-color': brandInk,
      'shadow-xs-opacity': 0.08,
      'shadow-sm-opacity': 0.1,
      'shadow-md-opacity': 0.12,
      'shadow-lg-opacity': 0.14,
      'shadow-xl-opacity': 0.16,
    },
  },
  dark: {
    dark: true,
    colors: {
      primary: '#2F9E5F',
      'on-primary': '#fff',
      'primary-darken-1': '#248A4F',
      secondary: '#D4B84A',
      'on-secondary': '#14261A',
      'secondary-darken-1': '#C0A53C',
      success: '#2F9E5F',
      'on-success': '#fff',
      'success-darken-1': '#248A4F',
      info: '#3D9BB8',
      'on-info': '#fff',
      'info-darken-1': '#31819A',
      warning: brandGold,
      'on-warning': '#14261A',
      'warning-darken-1': '#E0B400',
      error: '#E23B4A',
      'on-error': '#fff',
      'error-darken-1': '#CE1126',
      background: '#121A15',
      'on-background': '#E8EDE6',
      surface: '#1B2620',
      'on-surface': '#E8EDE6',
      'grey-50': '#161F19',
      'grey-100': '#1B2620',
      'grey-200': '#24312A',
      'grey-300': '#3A4A41',
      'grey-400': '#5A6B60',
      'grey-500': '#849489',
      'grey-600': '#A8B5AC',
      'grey-700': '#C2CCC5',
      'grey-800': '#D7DFD9',
      'grey-900': '#E8EDE6',
      'grey-light': '#24312A',
      'perfect-scrollbar-thumb': '#3A4A41',
      'skin-bordered-background': '#1B2620',
      'skin-bordered-surface': '#1B2620',
    },
    variables: {
      'code-color': brandGold,
      'overlay-scrim-background': '#0A100C',
      'tooltip-background': '#E8EDE6',
      'overlay-scrim-opacity': 0.6,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#E8EDE6',
      'border-opacity': 0.12,
      'table-header-color': '#2A3830',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.4,
      'switch-disabled-track-opacity': 0.4,
      'switch-disabled-thumb-opacity': 0.8,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#2A3830',
      'shadow-key-umbra-color': '#050805',
      'shadow-xs-opacity': 0.16,
      'shadow-sm-opacity': 0.18,
      'shadow-md-opacity': 0.2,
      'shadow-lg-opacity': 0.22,
      'shadow-xl-opacity': 0.24,
    },
  },
};

export default themes;
