export default [
  { heading: 'e-Parapheur' },
  {
    title: 'Mon parapheur',
    icon: { icon: 'tabler-briefcase' },
    to: 'parapheur',
    action: 'read',
    subject: 'Parapheur',
  },
  {
    title: 'Nouveau document',
    icon: { icon: 'tabler-file-plus' },
    to: 'parapheur-nouveau',
    action: 'create',
    subject: 'Document',
  },
  {
    title: 'Bureau DG',
    icon: { icon: 'tabler-layout-dashboard' },
    to: 'parapheur-dg',
    action: 'read',
    subject: 'DashboardDg',
  },
  {
    title: 'Administration',
    icon: { icon: 'tabler-shield-cog' },
    to: 'parapheur-admin',
    action: 'manage',
    subject: 'all',
  },
  {
    title: 'Instructions',
    icon: { icon: 'tabler-list-check' },
    to: 'parapheur-instructions',
    action: 'manage',
    subject: 'Instruction',
  },
  {
    title: 'Réunions',
    icon: { icon: 'tabler-users-group' },
    action: 'read',
    subject: 'Meeting',
    children: [
      {
        title: 'Tableau de bord',
        icon: { icon: 'tabler-layout-dashboard' },
        to: 'parapheur-reunions',
        action: 'read',
        subject: 'Meeting',
      },
      {
        title: 'Calendrier',
        icon: { icon: 'tabler-calendar' },
        to: 'parapheur-reunions-calendrier',
        action: 'read',
        subject: 'Meeting',
      },
      {
        title: 'Décisions',
        icon: { icon: 'tabler-gavel' },
        to: 'parapheur-reunions-decisions',
        action: 'read',
        subject: 'Meeting',
      },
    ],
  },
  {
    title: 'Agenda & RDV',
    icon: { icon: 'tabler-calendar-event' },
    action: 'read',
    subject: 'Appointment',
    children: [
      {
        title: 'Tableau de bord',
        icon: { icon: 'tabler-layout-dashboard' },
        to: 'parapheur-agenda',
        action: 'read',
        subject: 'Appointment',
      },
      {
        title: 'Agenda',
        icon: { icon: 'tabler-calendar' },
        to: 'parapheur-agenda-calendrier',
        action: 'read',
        subject: 'Appointment',
      },
      {
        title: 'Demandes',
        icon: { icon: 'tabler-inbox' },
        to: 'parapheur-agenda-demandes',
        action: 'read',
        subject: 'Appointment',
      },
      {
        title: 'À valider',
        icon: { icon: 'tabler-checks' },
        to: 'parapheur-agenda-avalider',
        action: 'validate',
        subject: 'Appointment',
      },
      {
        title: 'Mes rendez-vous',
        icon: { icon: 'tabler-user-check' },
        to: 'parapheur-agenda-mes-rdv',
        action: 'read',
        subject: 'Appointment',
      },
      {
        title: 'Indisponibilités',
        icon: { icon: 'tabler-calendar-off' },
        to: 'parapheur-agenda-indisponibilites',
        action: 'manage',
        subject: 'Appointment',
      },
    ],
  },
  {
    title: 'Mon espace documentaire',
    icon: { icon: 'tabler-cloud' },
    action: 'read',
    subject: 'Workspace',
    children: [
      {
        title: 'Accueil',
        icon: { icon: 'tabler-home' },
        to: 'espace',
        action: 'read',
        subject: 'Workspace',
      },
      {
        title: 'Mes dossiers',
        icon: { icon: 'tabler-folder' },
        to: 'espace-dossiers',
        action: 'read',
        subject: 'Workspace',
      },
      {
        title: 'Mes documents',
        icon: { icon: 'tabler-files' },
        to: 'espace-documents',
        action: 'read',
        subject: 'Workspace',
      },
      {
        title: 'Partagés avec moi',
        icon: { icon: 'tabler-share' },
        to: 'espace-partages',
        action: 'read',
        subject: 'Workspace',
      },
      {
        title: 'Espaces collaboratifs',
        icon: { icon: 'tabler-users' },
        to: 'espace-collaboratifs',
        action: 'read',
        subject: 'Workspace',
      },
      {
        title: 'Favoris',
        icon: { icon: 'tabler-star' },
        to: 'espace-favoris',
        action: 'read',
        subject: 'Workspace',
      },
      {
        title: 'Récents',
        icon: { icon: 'tabler-history' },
        to: 'espace-recents',
        action: 'read',
        subject: 'Workspace',
      },
      {
        title: 'Recherche',
        icon: { icon: 'tabler-search' },
        to: 'espace-recherche',
        action: 'read',
        subject: 'Workspace',
      },
      {
        title: 'Bibliothèque de références',
        icon: { icon: 'tabler-books' },
        to: 'espace-bibliotheque',
        action: 'read',
        subject: 'Library',
      },
      {
        title: 'Corbeille',
        icon: { icon: 'tabler-trash' },
        to: 'espace-corbeille',
        action: 'read',
        subject: 'Workspace',
      },
      {
        title: 'Administration quotas',
        icon: { icon: 'tabler-database-cog' },
        to: 'espace-admin',
        action: 'manage',
        subject: 'WorkspaceAdmin',
      },
    ],
  },
  {
    title: 'GED',
    icon: { icon: 'tabler-folders' },
    action: 'read',
    subject: 'Ged',
    children: [
      {
        title: 'Tableau de bord',
        icon: { icon: 'tabler-layout-dashboard' },
        to: 'ged',
        action: 'read',
        subject: 'Ged',
      },
      {
        title: 'Tous les documents',
        icon: { icon: 'tabler-files' },
        to: 'ged-documents',
        action: 'read',
        subject: 'Ged',
      },
      {
        title: 'Mes documents',
        icon: { icon: 'tabler-folder-user' },
        to: 'ged-mes-documents',
        action: 'read',
        subject: 'Ged',
      },
      {
        title: 'À traiter',
        icon: { icon: 'tabler-inbox' },
        to: 'ged-a-traiter',
        action: 'read',
        subject: 'Ged',
      },
      {
        title: 'Favoris',
        icon: { icon: 'tabler-star' },
        to: 'ged-favoris',
        action: 'read',
        subject: 'Ged',
      },
      {
        title: 'Récemment consultés',
        icon: { icon: 'tabler-history' },
        to: 'ged-recents',
        action: 'read',
        subject: 'Ged',
      },
      {
        title: 'Plan de classement',
        icon: { icon: 'tabler-sitemap' },
        to: 'ged-classification',
        action: 'read',
        subject: 'Ged',
      },
      {
        title: 'Recherche avancée',
        icon: { icon: 'tabler-search' },
        to: 'ged-recherche',
        action: 'read',
        subject: 'Ged',
      },
      {
        title: 'Archives',
        icon: { icon: 'tabler-archive' },
        to: 'ged-archives',
        action: 'read',
        subject: 'Ged',
      },
      {
        title: 'Nouveau document GED',
        icon: { icon: 'tabler-file-plus' },
        to: 'ged-nouveau',
        action: 'create',
        subject: 'Ged',
      },
      {
        title: 'Administration GED',
        icon: { icon: 'tabler-settings' },
        to: 'ged-admin',
        action: 'manage',
        subject: 'GedAdmin',
      },
    ],
  },
  {
    title: 'Reporting',
    icon: { icon: 'tabler-chart-bar' },
    to: 'parapheur-reporting',
    action: 'read',
    subject: 'Reporting',
  },
  {
    title: 'Délégations',
    icon: { icon: 'tabler-user-share' },
    to: 'parapheur-delegations',
    action: 'read',
    subject: 'DashboardDg',
  },
  { heading: 'Configuration' },
  {
    title: 'Paramètres',
    icon: { icon: 'tabler-settings' },
    children: [
      {
        title: 'Structures',
        icon: { icon: 'tabler-building-community' },
        to: 'parapheur-structures',
        action: 'manage',
        subject: 'Structure',
      },
      {
        title: 'Utilisateurs',
        icon: { icon: 'tabler-users' },
        to: 'parapheur-users',
        action: 'manage',
        subject: 'User',
      },
      {
        title: 'Rôles & permissions',
        icon: { icon: 'tabler-lock-access' },
        to: 'parapheur-roles',
        action: 'manage',
        subject: 'Role',
      },
      {
        title: 'Types de documents',
        icon: { icon: 'tabler-file-description' },
        to: 'parapheur-document-types',
        action: 'manage',
        subject: 'DocumentType',
      },
      {
        title: 'Types de réunions',
        icon: { icon: 'tabler-category' },
        to: 'parapheur-meeting-types',
        action: 'manage',
        subject: 'MeetingType',
      },
      {
        title: 'Modèles réunions',
        icon: { icon: 'tabler-template' },
        to: 'parapheur-meeting-templates',
        action: 'manage',
        subject: 'MeetingTemplate',
      },
      {
        title: 'Types de rendez-vous',
        icon: { icon: 'tabler-calendar-stats' },
        to: 'parapheur-appointment-types',
        action: 'manage',
        subject: 'AppointmentType',
      },
      {
        title: 'Circuits',
        icon: { icon: 'tabler-git-branch' },
        to: 'parapheur-workflows',
        action: 'manage',
        subject: 'all',
      },
      {
        title: 'Journal d’audit',
        icon: { icon: 'tabler-history' },
        to: 'parapheur-audit',
        action: 'read',
        subject: 'AuditLog',
      },
    ],
  },
]
